services:
  - type: worker
    name: naukri-profile-updater
    env: docker
    plan: free
    dockerCommand: npm run schedule
    envVars:
      - key: NAUKRI_EMAIL
        sync: false
      - key: NAUKRI_PASSWORD
        sync: false
